Implement statistics panel for a Settings item #2313
enonic/app-contentstudio pull request #2356
Opened 2020-10-08 09:50 UTC by ashklianko

2020-10-13 12:56 UTC, alansemenov requested changes
1. Increase font size of the layer's display name to be the same as principal name in the User's app (34px). Now the main header has the same font size as subsection headers and this looks strange.
2. Show full "path" under layer's display name: "_grandparentLayer/parentLayer/thisLayer_"
3. Remove "_Roles_" subsection for the Default project
4. Show language display name instead of language code (unless it requires an additional request, if it does then drop it).

2020-10-13 12:56 UTC, alansemenov commented
There are also Codacy [audit issues](https://app.codacy.com/manual/enonic/app-contentstudio/pullRequest?prid=6305041) to fix.

2020-10-15 08:19 UTC, ashklianko commented
Updated!

2020-10-19 20:07 UTC, alansemenov approved these changes

2020-10-19 20:07 UTC, merged