Enable Revert action for inherited, localised content #2391
enonic/app-contentstudio pull request #2394
Opened 2020-10-21 12:46 UTC by ashklianko

2020-10-21 12:46 UTC, ashklianko commented
Requires ContentSummary: add inheritance checks for Name and Parent #1511

2020-10-21 14:43 UTC, sigdestad commented
Is it revert, or reset? I think it should be "Reset" as revert is a version history thing.

2020-10-23 11:19 UTC, alansemenov requested changes

2020-10-23 11:19 UTC, alansemenov commented on src/main/resources/assets/js/app/wizard/action/ContentWizardActions.ts
> +                    return (this.content.getInherit().length * 2) < Object.keys(ContentInheritType).length;
Let's implement `isFullyInherited` in `ContentSummaryAndCompareStatus` and have all the checks there.

2020-10-23 15:40 UTC, alansemenov approved these changes

2020-10-23 15:40 UTC, merged