Project Statistics Panel is not refreshed after updating the project …
enonic/app-contentstudio pull request #2620
Opened 2020-12-08 08:19 UTC by ashklianko

…#2608

2020-12-09 14:57 UTC, alansemenov requested changes

2020-12-09 14:57 UTC, alansemenov commented on src/main/resources/assets/js/app/settings/browse/SettingsBrowsePanel.ts
> +                                          : null;
You could do 

`const previewItemId: string = this.getBrowseItemPanel().getStatisticsItem()?.getModel().getId();`

2020-12-09 14:57 UTC, alansemenov commented on src/main/resources/assets/js/app/settings/browse/SettingsBrowsePanel.ts
> +                this.getBrowseItemPanel().togglePreviewForItem(this.dataToBrowseItem(updatePreviewItemData));
Can we move this whole handler into a separate method? It's quite heavy...

2020-12-09 21:30 UTC, ashklianko commented
Updated

2020-12-10 07:46 UTC, alansemenov approved these changes

2020-12-10 07:46 UTC, merged