Limit double-click response area to the name viewer #2803
enonic/app-contentstudio pull request #2808
Opened 2021-01-21 11:53 UTC by ashklianko

2021-01-26 15:40 UTC, alansemenov approved these changes

2021-01-26 15:47 UTC, alansemenov requested changes

2021-01-26 15:47 UTC, alansemenov commented on src/main/resources/assets/js/app/browse/ContentTreeGrid.ts
> +        if (data && data.cell === 0) {
`if (data?.cell === 0)`

2021-01-26 15:47 UTC, alansemenov commented on src/main/resources/assets/js/app/browse/ContentTreeGrid.ts
> +        if (event && event.target && event.target.classList && event.target.classList.contains('toggle')) {
`if (event?.target?.classList?.contains('toggle'))`

2021-01-26 16:27 UTC, ashklianko commented
Updated

2021-01-27 07:53 UTC, alansemenov approved these changes

2021-01-27 07:53 UTC, merged