Hide static part of a long path in the Content Wizard #1499
enonic/app-contentstudio pull request #2884
Opened 2021-02-17 14:30 UTC by ashklianko

To avoid overcomplicated logic of wrapping/unwrapping static path part and calculating it's length on value change/resize:
1. Using flex styling and showing static part with title 
2. Removed redundant elements
3. Letting dynamic input grow as much as needed and static path shrink down to zero

@alansemenov please check if this approach is appropriate

Requires https://github.com/enonic/lib-admin-ui/pull/1802

2021-02-22 20:44 UTC, ashklianko commented
Fixed merge conflicts

2021-02-23 16:09 UTC, alansemenov commented on src/main/resources/assets/styles/wizard/content-wizard-panel.less
> -      }
This piece of code used to fix this issue:

![image](https://user-images.githubusercontent.com/11612490/108871500-82669700-75f9-11eb-80b1-f601217f2902.png)

2021-02-23 16:10 UTC, alansemenov requested changes
![image](https://user-images.githubusercontent.com/11612490/108871883-e5582e00-75f9-11eb-8429-b7598e7fec48.png)

The icon should be vertically centred

2021-02-23 16:17 UTC, alansemenov commented
Plenty of space here to fit the entire path, but both display name and path are truncated:

![image](https://user-images.githubusercontent.com/11612490/108872804-de7deb00-75fa-11eb-9d40-cc5c18d6b5dd.png)

2021-02-23 16:18 UTC, ashklianko commented
> Plenty of space here to fit the entire path, but both display name and path are truncated:
> 
> ![image](https://user-images.githubusercontent.com/11612490/108872804-de7deb00-75fa-11eb-9d40-cc5c18d6b5dd.png)

I've limited length to 660 px to be same as max length of wizard step forms

2021-02-23 16:29 UTC, alansemenov commented
> I've limited length to 660 px to be same as max length of wizard step forms

Ah, that's why... Ok, so this one is correct then :)

2021-02-24 12:16 UTC, ashklianko commented
Updated, also moved minimize arrrow button to a new place in a toolbar

2021-02-25 11:56 UTC, alansemenov approved these changes

2021-02-25 11:56 UTC, merged