Implement a new way of displaying inbound references in the Delete di…
enonic/app-contentstudio pull request #3272
Opened 2021-06-30 08:32 UTC by ashklianko

…alog #3260

2021-07-05 11:06 UTC, alansemenov requested changes
One more thing (that should've been mentioned in the original task description): we should change the order of child items so that the ones with the inbound references are shown on top of the list (just like we do with invalid/in progress items in the Publish dialog).

2021-07-05 11:06 UTC, alansemenov commented on modules/lib/src/main/resources/i18n/dialogs.properties
> +dialog.delete.hasInbound.part1=Inbound dependencies!
Can you rename `dialog.delete.dependencies` to `dialog.delete.hasInbound.part1` (and add "!") in all other language files as well, so that we could reuse the existing translations of this phrase?

2021-07-05 11:06 UTC, alansemenov commented
There's also some Codacy issues:

![image](https://user-images.githubusercontent.com/11612490/124462244-cd579e80-dd91-11eb-8092-5cd6c8b6f9a6.png)

2021-07-08 12:07 UTC, ashklianko commented
Updated

2021-07-12 09:23 UTC, alansemenov approved these changes
One more thing, that should've been mentioned in the original task description

2021-07-12 09:24 UTC, merged