Incorrect validation message for an invalid required occurrence #3823
enonic/app-contentstudio pull request #3855
Opened 2021-11-19 08:55 UTC by ashklianko

-For case with invalid occurrence for min=1 max=1 replacing InputValidationRecording with one that will trigger custom error

2021-11-24 08:36 UTC, alansemenov requested changes
Not completely there yet...
1. Error messages for occurrences should be hidden by default, user should click "Show details" to see them. Check how it's done for attachments.

2. Even though an occurrence has a custom validation error, the input itself still has "`valid`" class on it. This results in green border around invalid input
![image](https://user-images.githubusercontent.com/11612490/143202743-0f8509f5-32f7-46dc-8f92-b7f75b945619.png)

3. A bad one. After adding a **valid** occurrence to an input that already has an invalid one, the entire input (and the content itself) is marked as valid:
![image](https://user-images.githubusercontent.com/11612490/143202921-9f2d0dd0-8784-4528-8843-46b59210c5be.png)

2021-11-24 15:46 UTC, alansemenov commented
Correction: item 3 should be fixed in lib-admin-ui as described [here](https://github.com/enonic/lib-admin-ui/pull/2276#pullrequestreview-815081352). Maybe some of the first two should also be fixed in lib-admin-ui.

2021-11-27 14:39 UTC, ashklianko commented
Updated in lib-admin-ui

2021-11-29 19:34 UTC, alansemenov approved these changes

2021-11-29 19:35 UTC, merged