Server-side error when archiving content #4291
enonic/app-contentstudio pull request #4333
Opened 2022-03-16 19:50 UTC by vbradnitski

2022-03-17 08:42 UTC, rymsha approved these changes

2022-03-23 15:26 UTC, ashklianko requested changes
Still getting same errors in console:  `Failed to translate node ...`

2022-03-23 15:29 UTC, vbradnitski commented
> Still getting same errors in console: `Failed to translate node ...`

the main fix in xp, here is just a small refactoring.

2022-03-24 15:28 UTC, ashklianko approved these changes

2022-03-25 09:47 UTC, merged