Support new widget interface for the Sidebar #4290
enonic/app-contentstudio pull request #4336
Opened 2022-03-17 20:36 UTC by ashklianko

2022-03-24 16:18 UTC, alansemenov requested changes

2022-03-24 16:18 UTC, alansemenov commented on modules/app/src/main/resources/admin/widgets/settings/settings.html
> +<widget id="settings-widget">
Let's use `widget-settings`. This will make it consistent with "regular" widgets, and for external widgets we will use "`widget-<appId>`".

2022-03-24 16:18 UTC, alansemenov commented on modules/app/webpack.config.js
> +        ]
This deletion now causes this:
![image](https://user-images.githubusercontent.com/11612490/159957552-7b650922-a8d8-4eb7-92b5-bba6544d13b0.png)

2022-03-24 16:18 UTC, alansemenov commented on modules/app/src/main/resources/assets/js/main.ts
> +        commonWrapper.onItemAdded((item) => {
Use `(item: App | Widget)` and check for instance type instead of checking for properties that might disappear or be renamed (`item['getUrlPath']`).

2022-03-24 16:18 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/util/WidgetHelper.ts
> +            return;
Should probably throw an exception or give a proper toast error if someone is trying to inject a widget without proper formatting (`<widget>` tag).

2022-03-24 16:18 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/util/WidgetHelper.ts
> +        widgetContainer.innerHTML = html;
Create an Element using `UIElement.fromHtmlElement` as early as possible, then use `Element.setHtml()` to ensure HTML gets escaped.

2022-03-28 20:28 UTC, alansemenov commented
A few more things to fix:
* Change attributes for widget script to be data attributes with all-lower-case names
```html
<widget id="widget-settings">
    <script src="{{assetsUri}}" data-config-service-url="{{configServiceUrl}}" data-widget-id="widget-settings"></script>
</widget>
```
* In lib-admin-ui's `Element.ts` implement a version of `fromString` method which doesn't sanitize the string:

```Javascript
    static fromString(s: string, loadExistingChildren: boolean = true): Element {
        const sanitizedHtml: string = DOMPurify.sanitize(s);
        return Element.fromHtml(sanitizedHtml, loadExistingChildren);
    }

    static fromHtml(html: string, loadExistingChildren: boolean = true): Element {
        const htmlEl = $(html).get(0);

        if (!htmlEl) {
            return null;
        }

        let parentEl: Element;

        if (htmlEl && htmlEl.parentElement) {
            parentEl = Element.fromHtmlElement(htmlEl.parentElement);
        }

        return this.fromHtmlElement(htmlEl, loadExistingChildren, parentEl);
    }
````

* Use this new method inside `injectWidgetHtml`. We don't really need sanitisation since we now enforce Content Security Policy in Content Studio. Note validation of the root element to have `<widget>` tag.

```Javascript
    static injectWidgetHtml(html: string, target: UIElement): { scriptElements: HTMLScriptElement[], widgetContainer: UIElement } {
        const widgetContainer: UIElement = UIElement.fromHtml(html);
        if (widgetContainer?.getHTMLElement().tagName !== 'WIDGET') {
            throw 'Widget contents must be wrapped inside <widget></widget> tags';
        }

        const scriptElements: HTMLScriptElement[] = WidgetHelper.injectScriptsToHead(widgetContainer);
        target.appendChild(resultElement);

        return {scriptElements, widgetContainer};
    }
````

* `injectWidgetElementInto` (interesting name) is no longer needed.

2022-03-29 07:01 UTC, ashklianko commented
Updated

2022-03-29 09:44 UTC, alansemenov approved these changes

2022-03-29 09:45 UTC, merged