Removed download tab and added media content support (#4659)
enonic/app-contentstudio pull request #4665
Opened 2022-06-09 17:58 UTC by reisfmb

2022-06-10 15:27 UTC, alansemenov requested changes

2022-06-10 15:27 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +    private static mediaInliePrefix: string = 'media://inline/';
Typo. Should be `mediaInli_n_ePrefix`

2022-06-10 15:27 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +                return this.link.replace(LinkModalDialog.mediaInliePrefix, StringHelper.EMPTY_STRING);
Please use curly brackets inside `if`... body, even if it's a one-liner.

2022-06-10 15:27 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +            if (this.link && this.isDownloadLink())
You repeat `if (this.link &&...)` three times.
It should be either

```Typescript
if (this.link) {
  if (this.isInlineLink()) {
    return ...
  }
  if (this.isDownloadLink()) {
    return ...
  }
  ...
}
```

or, even better:

```Typescript
if (!this.link) {
  return StringHelper.EMPTY_STRING;
}

if (this.isInlineLink()) {
    return ...
}
if (this.isDownloadLink()) {
  return ...
}
```

2022-06-10 15:27 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +    private createRadio(id: string): FormItem {
What if you need another radiogroup, will you call the new method `createRadio2`? :)  It's better to give method less generic names. In this case it should be something like "`createMediaOptionRadio`".

2022-06-10 15:27 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        const radio = new RadioGroup('radio');
Same here, use less generic/more explanatory names.

2022-06-10 15:27 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +            formRadio =  $(radio.getHTMLElement()).closest('.input-view');
Any way to avoid using jquery here?

2022-06-10 15:27 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        let formRadio: JQuery<HTMLElement>;
const

2022-06-10 15:27 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        return selectedContent ? selectedContent.getType().getApplicationKey().getName() === 'media' : false;
Use `selectedContent.getType().isMedia()`

2022-06-10 15:27 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +                const contentSelectorSelectedContent = contentSelector.getSelectedContent();
It feels a bit strange to assign listener of content selector's `valuechanged` event inside `onrendered` listener of a totally different control. It's better to assign this listener right after the content selector is created

2022-06-10 15:27 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +                if (event.getNewValue() === MediaContentRadioAction.LINK) {
Same here. The listener should be assigned after the radio group is created.

2022-06-10 16:43 UTC, reisfmb commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        return selectedContent ? selectedContent.getType().getApplicationKey().getName() === 'media' : false;
Not behaving as expected...

https://user-images.githubusercontent.com/67838246/173112753-7a677013-b13b-4fe2-8bc1-5fde5285d866.mp4

2022-06-10 16:46 UTC, reisfmb commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        let formRadio: JQuery<HTMLElement>;
I think it should be let since the code will use `formRadio` in the `contentSelector.onValueChanged`

2022-06-10 16:49 UTC, reisfmb commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +            formRadio =  $(radio.getHTMLElement()).closest('.input-view');
Yes, we can recursively call `getParentElement` on the radio and keep comparing its class to the one I'm looking for. Should we do it like that avoid Jquery?

2022-06-13 10:10 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        let formRadio: JQuery<HTMLElement>;
Oh, sorry - of course.

2022-06-13 10:24 UTC, alansemenov requested changes
Also remove `createMediaSelectorBuilder` as it's no longer used.

2022-06-13 10:24 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        contentSelector.onValueChanged(() => {
This should also be moved to `createSelector`. If the reason for assigning an event listener to, for example, a content selector inside `createRadio` method is to be able to easily get a hold of the radio control, then don't hesitate to assign controls to class-wide properties.

Schematic example:

```Typescript
private mediaOptionsRadioGroup: FormItem;
private contentSelector: FormItem;

createMediaOptionsRadioGroup() {
  this.mediaOptionsRadioGroup = ...;
  this.mediaOptionsRadioGroup.whenRendered = () => {
      this.contentSelector.doBlaBla...
  }
}

createContentSelector() {
  this.contentSelector = ...;
  this.contentSelector.whenRendered = () => {
      this.mediaOptionsRadioGroup.doBlaBla...
  }
}
```

2022-06-13 10:24 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        return selectedContent ? selectedContent.getType().getApplicationKey().getName() === 'media' : false;
Yes, it should be `selectedContent.getType().isDescendantOfMedia()`

2022-06-13 13:13 UTC, reisfmb commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +            formRadio =  $(radio.getHTMLElement()).closest('.input-view');
Yes, not using it anymore after the rebase.

2022-06-13 15:07 UTC, alansemenov approved these changes
Now we're talking!

2022-06-13 15:07 UTC, merged