Added anchor and query params to content tab(#4692)
enonic/app-contentstudio pull request #4734
Opened 2022-06-22 00:20 UTC by reisfmb

Also removed unused anchor tab code

2022-06-22 09:35 UTC, alansemenov requested changes

2022-06-22 09:35 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        const addButton: Button = new Button('Add');
Use the existing i18n resource.

2022-06-22 09:35 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        hideAnchorFormButton.addClass('remove-button transparent icon-close');
Extract to a separate method called `createRemoveButton` or something. You are using exactly the same button for query string params, no point in repeating the same code.

2022-06-22 09:35 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        this.paramsFormItem.removeChild(this.paramsFormItem.getInput().getParentElement());
What does this line do and why?

2022-06-22 09:35 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        const n = this.paramsFormIds.length
This should have a more explanatory name, not just `n`

2022-06-22 09:35 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +    private paramsFormIds: {keyId: string, valueId: string}[];
Use [Map](https://howtodoinjava.com/typescript/maps/) instead. This will allow you use `.set`, `.delete` etc.

2022-06-22 09:35 UTC, alansemenov commented on modules/lib/src/main/resources/i18n/dialogs.properties
> +dialog.link.queryparams.empty=No key / value occurrence can be empty
Change to "`All parameters must have a name and a value`"

2022-06-22 09:35 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        const keyFormItem = this.createFormItemWithPostponedValue(keyFormItemId, '', () => initialKey, null, 'Key');
Rename '`Key`' to '`Name`', and it should come from i18n.

2022-06-22 09:35 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        const valueFormItem = this.createFormItemWithPostponedValue(valueFormItemId, '', () => initialValue, null, 'Value');
"`Value`" should come from i18n.

2022-06-22 09:35 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> -        return this.createFormItem(formItemBuilder);
Can't remove this. We have a "hidden" feature for adding links to anchors on the same page. Can be tested as follows:
1. Use Anchor button (the one with the flag) in the editor toolbar to insert an anchor into the HTML text
2. Open the Link dialog.
3. You will see the "Anchor" tab and you can select your anchor from the dropdown to link to it.

![image](https://user-images.githubusercontent.com/11612490/174996500-e0ce209d-a561-438b-8a9a-273f451ef719.png)

![image](https://user-images.githubusercontent.com/11612490/174996665-eaf2b549-03e3-4312-9636-5276409af4e1.png)

2022-06-22 18:06 UTC, reisfmb commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +    private paramsFormIds: {keyId: string, valueId: string}[];
I don't see why Map would benefit since I'm using some array methods on it, such as reduce to create the query parameters string.

2022-06-22 18:20 UTC, reisfmb commented on modules/lib/src/main/resources/assets/js/app/inputtype/ui/text/dialog/LinkModalDialog.ts
> +        this.paramsFormItem.removeChild(this.paramsFormItem.getInput().getParentElement());
_**What does it do?**_
It removes the default `textInput` created by the `createFormItem` method since a `formItem` expects a `formItemBuilder` which requires an input in its constructor.

_**Why?**_
Because I want `paramsFormItem` to be a `formItem` without an input, since I only want to use it as a wrapper for all name / value pairs, to handle the validation of all pairs with a single validator.

2022-06-23 10:38 UTC, alansemenov requested changes
We have changed syntax of the expected link format in the [backend task](https://github.com/enonic/xp/issues/7571), so we have to make according changes in this one as well.

If there are query string params, they should be concatenated (separated with `&`), then Url Encoded, then added to the resulting link as query parameter:
`content://<id>?query=<url_encoded_value_of_the_concatenated_query_string>`

If there's anchor, it should be Url Encoded, then added to the resulting link as fragment parameter:
`content://<id>?fragment=<url_encoded_value_of_the_anchor_field>`

If there are both:
`content://<id>?query=<query_string>&fragment=<anchor>`

2022-06-27 09:14 UTC, alansemenov approved these changes

2022-06-27 09:14 UTC, merged