Fixed broken layout in roles form (#4578)
enonic/app-contentstudio pull request #4752
Opened 2022-06-27 17:47 UTC by reisfmb

2022-06-28 08:29 UTC, ashklianko requested changes

2022-06-28 08:29 UTC, ashklianko commented on modules/lib/src/main/resources/assets/styles/project/project-access-control.less
> +      width: 70%;
I would try to avoid using width for it, and update `.access-selector` to have a `flex-shrink: 0`

2022-06-28 08:31 UTC, ashklianko commented
Also when menu is expanded styling within looks weird:
![image](https://user-images.githubusercontent.com/4255706/176132489-0de82817-4fee-404d-bfda-f9e4ba5c7786.png)
Selection with a blue background should spread to entire width of a menu

2022-06-29 08:06 UTC, ashklianko commented
Good job, Bruno! 
Could you please also check why menu is not collapsing when opening other menu? It looks like this:
![image](https://user-images.githubusercontent.com/4255706/176385160-c1bf1c58-4c6f-45d5-b8a0-9a781cf7ff2b.png)

2022-06-29 08:07 UTC, ashklianko requested changes
Need to check why menus not collapsing

2022-06-29 22:22 UTC, reisfmb commented
@ashklianko 
[video-9719994-e7cf0a0a3e97d107f1a2f87633e76f66.webm](https://user-images.githubusercontent.com/67838246/176555615-f013b176-9472-4d7c-995a-29a5c945a227.webm)

2022-06-30 07:57 UTC, ashklianko requested changes

2022-06-30 07:57 UTC, ashklianko commented on modules/lib/src/main/resources/assets/js/app/settings/wizard/panel/form/element/ProjectAccessSelector.ts
> +    hideMenu(): void {
That is redundant if you don't perform any extra actions

2022-06-30 07:57 UTC, ashklianko commented on modules/lib/src/main/resources/assets/js/app/settings/wizard/panel/form/element/ProjectAccessControlEntryView.ts
> +    private projectACESelectedOptionsView: ProjectACESelectedOptionsView;
I think this is bad idea to pass and keep a reference to it's parent: in general class shouldn't know nothing about it's structure and it's parents

2022-06-30 07:57 UTC, ashklianko commented on modules/lib/src/main/resources/assets/js/app/settings/wizard/panel/form/element/ProjectAccessControlEntryView.ts
> +    constructor(projectACESelectedOptionsView: ProjectACESelectedOptionsView, ace: ProjectAccessControlEntry, readonly: boolean = false, ) {
Same comment as above

2022-06-30 07:57 UTC, ashklianko commented on modules/lib/src/main/resources/assets/js/app/settings/wizard/panel/form/element/ProjectAccessControlEntryView.ts
> +    private closeOtherAccessSelectors(): void {
I think the better solution would be to check `TabMenu.hideMenuOnOutsideClick` method

2022-06-30 19:32 UTC, reisfmb commented
@ashklianko 

menus not collapsing is fixed from this: https://github.com/enonic/lib-admin-ui/pull/2660

2022-06-30 21:03 UTC, ashklianko approved these changes

2022-06-30 21:09 UTC, merged