Fixed user count update on widget resize (#4575)
enonic/app-contentstudio pull request #4792
Opened 2022-07-04 15:09 UTC by alansemenov

2022-07-04 21:01 UTC, ashklianko requested changes

2022-07-04 21:01 UTC, ashklianko commented on modules/lib/src/main/resources/assets/js/app/security/UserAccessListItemView.ts
>              ResponsiveManager.onAvailableSizeChanged(this, this.resizeListener);
Seems we also don't need this and overridden `remove()` method :)
Responsive manager is also adding some classes describing size (in addition to reacting to size change), but they are not used in styling, thus we can remove it

2022-07-04 22:36 UTC, reisfmb commented
Close and reopening PR since build step was stuck:

build: _Expected — Waiting for status to be reported_

2022-07-05 06:57 UTC, ashklianko approved these changes

2022-07-06 07:58 UTC, merged