Filter requests: send params and don't construct NoQL search string o…
enonic/app-contentstudio pull request #4808
Opened 2022-07-07 07:19 UTC by ashklianko

…n the frontend #4786

-Totally removed NoQL from filter panel request
-Using DSL on the backend to process filter panel requests
-Some other classes still use queryExpr and will be fixed in other tasks
-Added tests

2022-07-07 14:34 UTC, alansemenov approved these changes
Looks fine. I'll leave review of the Java code to smart(er) people

2022-07-08 08:57 UTC, anatol-sialitski approved these changes

2022-07-13 13:51 UTC, vbradnitski requested changes

2022-07-13 13:51 UTC, vbradnitski commented on modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentQueryJsonToContentQueryConverter.java
> +        return contentQueryJson.getQuerySort().stream()
It fails with NPE if getQuery() result is not null and getQuerySort() is null

2022-07-13 14:49 UTC, vbradnitski approved these changes

2022-07-13 20:36 UTC, merged