New Content dialog doesn't show content types from project apps #5104
enonic/app-contentstudio pull request #5115
Opened 2022-09-09 14:59 UTC by vbradnitski

2022-09-09 16:30 UTC, rymsha requested changes

2022-09-09 16:30 UTC, rymsha commented on modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/schema/content/FilterByContentResolver.java
> +            return Stream.of( defaultContentTypes, siteContentTypes, projectContentTypes )
How can site and project contentTypes coexist?
Ot is either project or site.

2022-09-12 11:16 UTC, rymsha approved these changes

2022-09-13 13:18 UTC, anatol-sialitski approved these changes

2022-09-14 15:51 UTC, merged