Workflow icon is missing a tooltip #5152
enonic/app-contentstudio pull request #5350
Opened 2022-10-25 13:58 UTC by ashklianko

2022-10-25 13:58 UTC, ashklianko commented
Will check tests first

2022-10-31 09:06 UTC, alansemenov requested changes
Instead of having comparisons like `this.status === WorkflowStateStatus.INVALID` all over the code, let's add static methods like these inside `WorkflowStateManager`:

```
static isReady(status: WorkflowStateStatus): boolean {
    return status === WorkflowStateStatus.READY;
}
```

2022-11-01 09:06 UTC, alansemenov requested changes

2022-11-01 09:06 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/WorkflowStateManager.ts
> +        toolbarIcon?.toggleClass(WorkflowStateStatus.IN_PROGRESS, this.status === WorkflowStateStatus.IN_PROGRESS);
`toolbarIcon?.toggleClass(WorkflowStateStatus.INVALID, WorkflowStateStatus.isInvalid(this.status));`

etc.

2022-11-01 13:52 UTC, ashklianko commented
Will work after https://github.com/enonic/app-contentstudio/pull/5383 merged

2022-11-01 15:44 UTC, alansemenov approved these changes

2022-11-01 15:44 UTC, merged