Issue 7312
enonic/app-contentstudio pull request #7475
Opened 2024-04-02 08:15 UTC by ashklianko

2024-04-02 10:21 UTC, ashklianko commented
Requires https://github.com/enonic/lib-admin-ui/pull/3518 and both pulls need to remove commits updating versions

2024-04-02 12:09 UTC, alansemenov requested changes

2024-04-02 12:09 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/ContentPanelStripHeader.ts
> +}
```suggestion
export interface ContentPanelStripHeaderConfig extends PanelStripHeaderConfig {
    optional?: boolean;
}
```

2024-04-02 12:09 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/ContentPanelStripHeader.ts
> +    protected options: ContentPanelStripHeaderOptions;
```suggestion
    protected config: ContentPanelStripHeaderConfig;
```

2024-04-02 12:09 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/ContentPanelStripHeader.ts
> +    }
```suggestion
    constructor(config: ContentPanelStripHeaderConfig) {
        super(config);
    }
```

2024-04-02 12:09 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/ContentPanelStripHeader.ts
> +        if (this.options.isOptional) {
```suggestion
        if (this.config.optional) {
```

2024-04-02 12:09 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/ContentPanelStripHeader.ts
> +        if (this.options.isOptional) {
```suggestion
        if (this.config.optional) {
```

2024-04-02 12:09 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/ContentWizardStepsPanel.ts
> +    }
```suggestion
    private isXDataStepFormOptional(wizardStepForm: WizardStepForm): boolean {
        return wizardStepForm instanceof XDataWizardStepForm && wizardStepForm.isOptional();
    }
```

2024-04-02 12:09 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/ContentWizardStepsPanel.ts
> +        if (this.isWizardStepFormOptional(wizardStepForm)) {
```suggestion
        if (this.isXDataStepFormOptional(wizardStepForm)) {
```

2024-04-02 12:09 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/ContentWizardStepsPanel.ts
> +        const isPanelOptional = this.isWizardStepFormOptional(wizardStepForm);
```suggestion
        const isPanelOptional = this.isXDataStepFormOptional(wizardStepForm);
```

2024-04-03 06:25 UTC, alansemenov requested changes

2024-04-03 06:25 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/ContentWizardStepsPanel.ts
> +        return wizardStepForm instanceof XDataWizardStepForm && wizardStepForm.isExpandable();
```suggestion
        return wizardStepForm instanceof XDataWizardStepForm && wizardStepForm.isOptional();
```

2024-04-03 08:38 UTC, alansemenov approved these changes

2024-04-03 09:06 UTC, merged