Warning when unpublishing items with published references #7500
enonic/app-contentstudio pull request #7522
Opened 2024-04-16 08:51 UTC by ashklianko

2024-04-17 11:52 UTC, alansemenov requested changes
If a content to be unpublished has two inbound references, one published and one unpublished, then clicking "Show references" will show both of them. We need to fix it so that only published references are shown (for the Delete dialog it should continue showing both).

<img width="755" alt="image" src="https://github.com/enonic/app-contentstudio/assets/11612490/fcb1b78e-9909-4427-9a01-ea9bc147bbd5">

<img width="788" alt="image" src="https://github.com/enonic/app-contentstudio/assets/11612490/11192ed3-8f4e-4699-8116-111f3cb344a7">

2024-04-26 09:14 UTC, alansemenov approved these changes
Great job 👍

2024-04-26 10:05 UTC, vbradnitski commented on modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java
> +    private ContentWithRefsResultJson resolveReferences(final ContentIds contentIds)
rename to _doResolveReferences_?

2024-04-26 10:05 UTC, vbradnitski commented on modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java
> +            .callWith( () -> contentService.getByIds( new GetContentByIdsParams( findResult.getContentIds() ) ) )
Here and in all other places it would better to move a ternary operator to the select of branch/context to avoid duplicating service calls.

2024-04-26 10:05 UTC, vbradnitski commented on modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java
> +            .callWith( () -> contentService.getByIds( new GetContentByIdsParams( findResult.getContentIds() ) ) )
or even move context creation to a separate method

2024-04-29 08:13 UTC, ashklianko commented on modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java
> +            .callWith( () -> contentService.getByIds( new GetContentByIdsParams( findResult.getContentIds() ) ) )
Done

2024-04-30 11:58 UTC, vbradnitski requested changes

2024-04-30 11:58 UTC, vbradnitski commented on modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java
> +        final boolean isMasterQuery = ContentConstants.BRANCH_MASTER.equals( params.getBranch() );
`final Branch branch = isMasterQuery ? ContentConstants.BRANCH_MASTER : ContentConstants.BRANCH_DRAFT;`

2024-04-30 15:35 UTC, ashklianko commented on modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java
> +        final boolean isMasterQuery = ContentConstants.BRANCH_MASTER.equals( params.getBranch() );
Updated

2024-05-03 07:30 UTC, vbradnitski commented on modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java
> +                .callWith( () -> doGetDependencies( params ) ) : doGetDependencies( params );
"callWith( () -> doGetDependencies( params ) ) : doGetDependencies( params );"

There is should be one call of "doGetDependencies"

2024-05-04 14:55 UTC, merged