Duplicate message about failed rendering in the editor panel #7482
enonic/app-contentstudio pull request #7526
Opened 2024-04-17 15:17 UTC by ashklianko

2024-04-23 12:41 UTC, alansemenov requested changes
The problem now is that it stopped warning about missing apps at all. It says "check the logs for errors" but there are no errors in the logs.

The logic should be like this:

1. If HEAD returns 418 AND there are missing apps, then the message about missing apps should have higher priority than other messages.
2. If HEAD returns 200 AND there are missing apps, then we don't need to care about missing apps and show the message about them.
3. If HEAD returns 418 AND there are no missing apps, then show relevant message (like now).

![image](https://github.com/enonic/app-contentstudio/assets/11612490/e7e101dd-da43-4fc2-a382-3357cee7b912)

2024-04-23 12:41 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts
> +            if (before !== after) { // can also sort arrays and check array equality
This is too philosophical. Can we rename this to `currentAppCount` and `fetchedAppCount`?

2024-04-26 11:00 UTC, alansemenov requested changes

2024-04-26 11:00 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
> +    }
```suggestion
        if (this.isRenderable) {
            this.clearErrorMissingApps();
            return;
        }
        
        if (!this.hasPage) {  // no page
            this.clearErrorMissingApps();
            this.placeholder?.setHasControllersMode(this.hasAvailableControllers);
            return;
        }

        if (this.hasMissingApps) { // not renderable due to missing apps
          this.setErrorMissingApps();
          return;
        }
                
        // not renderable due to rendering error
        this.clearErrorMissingApps();

        if (!this.placeholder) {
            this.createLiveEditPagePlaceholder();
        }

        this.frameContainer?.hide();
        this.placeholder.setPageIsNotRenderableMode();
        this.placeholder.show();
    }
```

2024-04-26 11:00 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
> +    }
Can probably be refactored as well, since `this.clearErrorMissingApps()` is called in 3 out of 4 cases, so there's no point in repeating it.

2024-04-26 11:01 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
> +    }
Functionality now works fine, btw. Great job

2024-04-26 13:59 UTC, ashklianko commented on modules/lib/src/main/resources/assets/js/app/wizard/page/LiveFormPanel.ts
> +    }
Updated

2024-04-26 14:04 UTC, alansemenov approved these changes

2024-04-29 08:20 UTC, merged