Include text-based inputs inside X-data when translating #8009
enonic/app-contentstudio pull request #8010
Opened 2024-10-30 13:54 UTC by ashklianko

Requires https://github.com/enonic/lib-admin-ui/pull/3770

2024-10-30 15:01 UTC, edloidas requested changes
Nice! Just a few stylistic improvements.

2024-10-30 15:01 UTC, edloidas commented on modules/lib/src/main/resources/assets/js/app/ai/AI.ts
> +        })) : [];
```suggestion
        return this.content?.getAllExtraData().map((extraData: ExtraData) => ({
            name: extraData.getName().toString(),
            fields: extraData.getData().toJson(),
        })) ?? [];
```

2024-10-30 15:01 UTC, edloidas commented on modules/lib/src/main/resources/assets/js/app/ai/AI.ts
> +        }): [];
```suggestion
        return this.xDataSchemas?.map(xData => {
            return {
                form: xData.toForm().toJson(),
                name: xData.getName(),
            };
        }) ?? [];
```

2024-10-30 15:01 UTC, edloidas commented on modules/lib/src/main/resources/assets/js/app/ai/AI.ts
> +        return undefined;
```suggestion
        const xDataStepForm = XDataWizardStepForm.getXDataWizardStepForm(xDataName);
        return xDataStepForm ? AiHelper.getAiHelpersByParent(xDataStepForm).find(aiHelper => aiHelper.getDataPath() === path) : undefined;
```

2024-11-11 08:08 UTC, alansemenov approved these changes

2024-11-11 17:11 UTC, edloidas approved these changes

2024-11-11 19:27 UTC, merged