Live view
enonic/app-contentstudio pull request #8056
Opened 2024-11-13 14:53 UTC by pmi

2025-01-06 11:49 UTC, alansemenov requested changes
We need to have a bit more space both around and inside the dropdowns, it feels too crampled now. Also, the icons inside the toolbar are a bit too small - they should be of the same size as the preview icon.

Now (14x14):
![image](https://github.com/user-attachments/assets/10f7b272-b869-420f-a9b5-bbf779a4a213)

Should be (20x20):
![image](https://github.com/user-attachments/assets/46db1bc0-25fe-49c5-b1fb-2f453e95325c)

2025-01-06 11:49 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/view/toolbar/EmulatorDropdown.ts
> +            }
This dropdown doesn't have a filtering input, so we don't need `filter` config. If for some reason we do then we shouldn't repeat `searchString.toLowerCase()` 4 times.

2025-01-06 11:49 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/view/toolbar/PreviewWidgetDropdown.ts
> +            }
Same here - no need for `filter` since the dropdown is not filterable.

2025-01-06 11:49 UTC, alansemenov commented on modules/app/src/main/resources/admin/widgets/preview-json/preview-json.xml
> +  <description>Display in JSON format</description>
All of the preview widgets must have localised `display-name` and `description` (via i18n attribute). It's enough to add the localisation keys only to `phrases.properties`.

2025-01-06 11:49 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/view/ContentItemPreviewPanel.ts
> +                    // }, 500);
Remove the comments

2025-01-06 11:49 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/view/ContentItemPreviewPanel.ts
> +            }
Should have default fallback

2025-01-06 11:49 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/view/ContentItemPreviewPanel.ts
> +        case PREVIEW_TYPE.MISSING: {
Maybe replace with `default:`?

2025-01-06 11:49 UTC, alansemenov commented on modules/lib/src/main/resources/assets/js/app/view/ContentItemPreviewPanel.ts
> +        }
Can't we set this via CSS? If not, then we need to do `new ElementHelper(body)`, then use setters from ElementHelper (`setDisplay`, `setMaxWidth` etc)

2025-01-07 14:55 UTC, pmi commented on modules/lib/src/main/resources/assets/js/app/view/ContentItemPreviewPanel.ts
> +        }
No, it can't be done with css because we modify contents of iframe that is populated by the browser.
`ElementHelper` doesn't work either unfortunately, because it doesn't have access to fields like `justifyContent` or `alignItems`

2025-01-08 12:38 UTC, alansemenov approved these changes
Great job, Pavel!

2025-01-09 08:32 UTC, merged